server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/loyalty

  datasource:
    url: jdbc:postgresql://localhost:5435/loyalty_db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  server-url: http://localhost:8085
  realm: loyalty
  client-id: loyalty-backend
  client-secret: YcceSjFecjtj3MthFQejmbjxH3LjQzG5

logging:
  level:
    com:
      example:
        loyalty: DEBUG