server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/loyalty

  datasource:
    url: jdbc:postgresql://localhost:5435/loyalty_db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true
keycloak:
  server-url: http://localhost:8080
  realm: loyalty
  client-id: loyalty-backend
  client-secret: aUNKISDoLUvSdQsHNFHlopqbU1gPrPBD

logging:
  level:
    com:
      example:
        loyalty: DEBUG